In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split,cross_val_score,cross_validate,GridSearchCV,RandomizedSearchCV
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
from sklearn.preprocessing import StandardScaler

In [2]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_colWidth',None)

In [3]:
df = pd.read_csv('train_cleaned.csv')

In [4]:
df.sample(5)

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
419084,60,1,4,120,231,0,0,172,1,2.8,2,0,7,0
27129,42,1,3,140,231,0,0,140,0,1.4,1,0,7,1
230379,57,1,2,110,239,0,0,173,0,1.2,1,0,3,0
283859,69,1,4,150,204,0,2,174,1,0.6,1,1,3,0
495224,63,1,4,120,256,0,0,156,1,1.5,2,0,7,1

In [5]:
df['Heart Disease'].value_counts()

Heart Disease
0    347546
1    282454
Name: count, dtype: int64

In [6]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=230)
scalar = StandardScaler()
x_train1 = scalar.fit_transform(x_train)
x_test1 = scalar.transform(x_test)
x1 = scalar.fit_transform(x)

In [14]:
dt1 = DecisionTreeClassifier()
dt1.fit(x_train,y_train)
y_pred1 = dt1.predict(x_test)
y_proba1 = dt1.predict_proba(x_test)[:,1]
print('Accuracy :',np.round(accuracy_score(y_test,y_pred1),3))
print('Precision :',np.round(precision_score(y_test,y_pred1),3))
print("Recall :",np.round(recall_score(y_test,y_pred1),3))
print('f1_score :',np.round(f1_score(y_test,y_pred1),3))
print('roc_auc :',np.round(roc_auc_score(y_test,y_proba1),3))

Accuracy : 0.827
Precision : 0.805
Recall : 0.809
f1_score : 0.807
roc_auc : 0.825

In [16]:
dt2 = DecisionTreeClassifier()
dt2.fit(x_train1,y_train)
y_pred1 = dt2.predict(x_test1)
y_proba1 = dt2.predict_proba(x_test1)[:,1]
print('Accuracy :',np.round(accuracy_score(y_test,y_pred1),3))
print('Precision :',np.round(precision_score(y_test,y_pred1),3))
print("Recall :",np.round(recall_score(y_test,y_pred1),3))
print('f1_score :',np.round(f1_score(y_test,y_pred1),3))
print('roc_auc :',np.round(roc_auc_score(y_test,y_proba1),3))

Accuracy : 0.826
Precision : 0.805
Recall : 0.808
f1_score : 0.807
roc_auc : 0.825

In [17]:
dt3 = DecisionTreeClassifier(criterion='entropy')
dt3.fit(x_train,y_train)
y_pred1 = dt3.predict(x_test)
y_proba1 = dt3.predict_proba(x_test)[:,1]
print('Accuracy :',np.round(accuracy_score(y_test,y_pred1),3))
print('Precision :',np.round(precision_score(y_test,y_pred1),3))
print("Recall :",np.round(recall_score(y_test,y_pred1),3))
print('f1_score :',np.round(f1_score(y_test,y_pred1),3))
print('roc_auc :',np.round(roc_auc_score(y_test,y_proba1),3))

Accuracy : 0.828
Precision : 0.806
Recall : 0.813
f1_score : 0.809
roc_auc : 0.827

In [19]:
dt4 = DecisionTreeClassifier(criterion='entropy')
dt4.fit(x_train1,y_train)
y_pred1 = dt4.predict(x_test1)
y_proba1 = dt4.predict_proba(x_test1)[:,1]
print('Accuracy :',np.round(accuracy_score(y_test,y_pred1),3))
print('Precision :',np.round(precision_score(y_test,y_pred1),3))
print("Recall :",np.round(recall_score(y_test,y_pred1),3))
print('f1_score :',np.round(f1_score(y_test,y_pred1),3))
print('roc_auc :',np.round(roc_auc_score(y_test,y_proba1),3))

Accuracy : 0.828
Precision : 0.806
Recall : 0.812
f1_score : 0.809
roc_auc : 0.827

In [20]:
dt5 = DecisionTreeClassifier(criterion='log_loss')
dt5.fit(x_train1,y_train)
y_pred1 = dt5.predict(x_test1)
y_proba1 = dt5.predict_proba(x_test1)[:,1]
print('Accuracy :',np.round(accuracy_score(y_test,y_pred1),3))
print('Precision :',np.round(precision_score(y_test,y_pred1),3))
print("Recall :",np.round(recall_score(y_test,y_pred1),3))
print('f1_score :',np.round(f1_score(y_test,y_pred1),3))
print('roc_auc :',np.round(roc_auc_score(y_test,y_proba1),3))

Accuracy : 0.828
Precision : 0.806
Recall : 0.812
f1_score : 0.809
roc_auc : 0.827

In [8]:
splitter = ['best','random']
criterian = ['gini','entropy','log_loss']
max_features = ['sqrt','log2',None,0.8,0.7,0.6,0.5]
max_depth = [3,5,7,9,11,13,15]
class_weight = [1,2,3,4,5]
ccp_alpha = [0.0, 0.001, 0.01]
accuracy = []
precision = []
recalls = []
f1_scores = []
roc_auc = []
splitter1 = []
max_depth1 = []
criterian1 = []
max_features1 = []
class_weight_0 = []
class_weight_1 = []
ccp_alpha1 = []
for depth in max_depth:
    for criteria in criterian:
        for split in splitter:
            for feature in max_features:
                for i in class_weight:
                    for alpha in ccp_alpha:
                        dt = DecisionTreeClassifier(criterion=criteria,max_depth=depth,splitter=split,
                                                    max_features=feature,class_weight={0:i,1:2*i},ccp_alpha=alpha)
                        dt.fit(x_train1,y_train)
                        y_pred = dt.predict(x_test1)
                        y_proba = dt.predict_proba(x_test1)[:,1]
                        accu = np.round(accuracy_score(y_test,y_pred),3)
                        preci = np.round(precision_score(y_test,y_pred),3)
                        recall = np.round(recall_score(y_test,y_pred),3)
                        f1 = np.round(f1_score(y_test,y_pred),3)
                        roc = np.round(roc_auc_score(y_test,y_proba),3)
                        accuracy.append(accu)
                        precision.append(preci)
                        recalls.append(recall)
                        f1_scores.append(f1)
                        roc_auc.append(roc)
                        max_depth1.append(depth)
                        criterian1.append(criteria)
                        splitter1.append(split)
                        max_features1.append(feature)
                        class_weight_0.append(i)
                        class_weight_1.append(2*i)
                        ccp_alpha1.append(alpha)

In [9]:
temp = pd.DataFrame({
        'max_depth':max_depth1,
        'criterian':criterian1,
        'splitter':splitter1,
        'max_features':max_features1,
        'class_weight_o':class_weight_0,
        'class_weight_1':class_weight_1,
        'ccp_alpha':ccp_alpha1,
        'accuracy':accuracy,
        'precision':precision,
        'recall':recalls,
        'f1_score':f1_scores,
        'roc_auc':roc_auc,
    })

In [10]:
temp.to_csv('all_combination_param.csv',index=False)

In [12]:
temp.shape

(4410, 12)

In [28]:
temp.head()

,max_depth,criterian,splitter,max_features,class_weight_o,class_weight_1,ccp_alpha,accuracy,precision,recall,f1_score,roc_auc
0,3,gini,best,sqrt,1,2,0.000,0.811,0.753,0.862,0.804,0.883
1,3,gini,best,sqrt,1,2,0.001,0.796,0.717,0.900,0.798,0.881
2,3,gini,best,sqrt,1,2,0.010,0.739,0.690,0.757,0.722,0.784
3,3,gini,best,sqrt,2,4,0.000,0.788,0.717,0.872,0.787,0.888
4,3,gini,best,sqrt,2,4,0.001,0.760,0.687,0.853,0.761,0.839

In [31]:
temp['roc_auc'].sort_values()

527     0.680
553     0.699
2021    0.708
947     0.727
112     0.734
449     0.758
3263    0.759
343     0.760
122     0.769
125     0.773
117     0.773
758     0.783
2       0.784
1904    0.785
337     0.785
16      0.786
203     0.789
333     0.793
121     0.795
529     0.797
2000    0.797
329     0.797
550     0.797
958     0.799
650     0.799
116     0.800
600     0.801
526     0.802
3890    0.805
752     0.807
547     0.809
742     0.812
411     0.812
2642    0.812
741     0.813
2018    0.814
126     0.814
3893    0.815
1265    0.815
110     0.816
3173    0.816
107     0.817
320     0.817
335     0.818
119     0.819
3782    0.819
3902    0.820
326     0.820
2654    0.821
737     0.821
341     0.821
530     0.821
407     0.821
331     0.822
316     0.822
540     0.823
338     0.823
2648    0.824
1379    0.824
113     0.824
3896    0.825
344     0.825
552     0.826
836     0.826
537     0.827
1907    0.827
3887    0.827
20      0.827
1913    0.827
2651    0.827
2216    0.828
133     0.828
2729    0.828
219     0.828
962     0.828
3257    0.828
970     0.828
128     0.828
1268    0.829
3278    0.829
332     0.830
3899    0.830
1157    0.830
549     0.830
3272    0.831
109     0.831
788     0.831
2525    0.831
3347    0.832
740     0.832
632     0.832
525     0.832
548     0.832
1373    0.832
3071    0.832
1604    0.833
220     0.833
1286    0.833
3275    0.833
659     0.833
1910    0.834
3692    0.834
2099    0.834
127     0.835
3155    0.835
431     0.835
1451    0.835
1367    0.835
1388    0.835
15      0.835
23      0.835
965     0.836
17      0.836
2228    0.836
972     0.836
422     0.836
336     0.837
432     0.837
324     0.838
541     0.838
428     0.838
3170    0.838
118     0.838
108     0.839
638     0.839
2639    0.839
25      0.839
4       0.839
216     0.840
2636    0.840
327     0.840
3686    0.840
1055    0.841
321     0.841
1799    0.841
4316    0.841
129     0.841
120     0.842
319     0.842
2681    0.842
1289    0.842
1409    0.842
209     0.842
3269    0.842
2546    0.842
3794    0.842
193     0.843
1424    0.843
1166    0.843
1382    0.843
26      0.843
197     0.843
427     0.844
2627    0.844
539     0.845
3986    0.845
2054    0.845
2633    0.845
587     0.845
812     0.845
2024    0.845
223     0.845
440     0.845
3932    0.845
755     0.845
620     0.845
2687    0.845
3911    0.845
1898    0.845
185     0.845
3281    0.845
824     0.846
1178    0.846
2420    0.846
1901    0.846
2087    0.846
237     0.846
2837    0.846
743     0.847
3908    0.847
1448    0.847
966     0.847
325     0.847
1454    0.847
1892    0.847
28      0.847
322     0.847
1271    0.847
437     0.848
1177    0.848
974     0.848
115     0.848
542     0.848
3983    0.848
2540    0.848
415     0.849
532     0.849
2702    0.849
827     0.849
1583    0.849
393     0.849
2531    0.850
2675    0.850
2666    0.850
2069    0.850
803     0.850
27      0.850
3284    0.850
143     0.850
3806    0.850
3305    0.850
210     0.850
1400    0.850
173     0.850
770     0.850
767     0.850
656     0.850
3974    0.850
1433    0.850
2048    0.850
1469    0.850
3326    0.850
164     0.850
3308    0.850
230     0.850
1274    0.850
815     0.850
3227    0.851
1394    0.851
2714    0.851
536     0.851
227     0.851
2696    0.851
4118    0.851
434     0.851
1445    0.851
3152    0.851
211     0.851
339     0.851
791     0.851
546     0.851
2672    0.851
647     0.852
3956    0.852
3359    0.852
2549    0.852
2225    0.853
2333    0.853
3935    0.853
3797    0.853
130     0.853
111     0.853
2723    0.853
3056    0.853
2645    0.853
3260    0.853
7       0.854
2630    0.854
3689    0.854
551     0.854
323     0.854
1403    0.854
2030    0.854
2027    0.854
3953    0.854
191     0.854
414     0.854
2015    0.854
3161    0.854
140     0.854
3944    0.854
2507    0.854
2327    0.854
21      0.854
1919    0.854
146     0.854
1175    0.855
419     0.855
429     0.855
746     0.855
2537    0.855
3062    0.855
200     0.855
184     0.855
591     0.855
950     0.855
1580    0.855
1575    0.855
3335    0.855
123     0.856
3803    0.856
3791    0.856
1895    0.856
179     0.856
1277    0.856
1262    0.856
1376    0.856
1358    0.856
3680    0.856
2102    0.856
1814    0.856
412     0.857
188     0.857
131     0.857
1370    0.857
2855    0.858
543     0.858
3476    0.858
80      0.858
2717    0.858
50      0.858
776     0.858
194     0.858
3800    0.858
1181    0.858
3266    0.858
1436    0.858
167     0.858
1439    0.858
739     0.858
105     0.858
3947    0.859
3239    0.859
3995    0.859
535     0.859
2012    0.859
1997    0.859
4217    0.859
2528    0.859
340     0.859
4115    0.860
2543    0.860
4334    0.860
3788    0.860
196     0.860
764     0.860
29      0.860
956     0.860
2684    0.860
604     0.860
2003    0.860
1322    0.860
328     0.860
2045    0.860
395     0.861
1415    0.861
3350    0.861
1381    0.861
86      0.861
3587    0.861
545     0.861
342     0.861
1076    0.861
3164    0.861
866     0.862
1172    0.862
2708    0.862
206     0.862
176     0.862
170     0.862
3494    0.862
4403    0.862
446     0.862
1466    0.863
845     0.863
182     0.863
3968    0.863
785     0.863
3344    0.863
2081    0.863
3980    0.863
3962    0.863
2051    0.863
3683    0.863
953     0.863
2660    0.863
3374    0.863
1418    0.863
3386    0.863
447     0.863
430     0.863
421     0.863
2006    0.863
3977    0.863
2438    0.863
134     0.863
149     0.863
839     0.864
3920    0.864
1406    0.864
3785    0.864
3356    0.864
707     0.864
773     0.864
1391    0.864
2093    0.864
3959    0.864
1457    0.864
1427    0.864
2669    0.864
1364    0.864
2066    0.864
794     0.864
710     0.864
1334    0.864
1313    0.864
1310    0.864
1307    0.864
2042    0.864
2063    0.864
2600    0.864
2618    0.864
1385    0.864
2036    0.864
1328    0.864
2588    0.864
53      0.864
3248    0.864
12      0.864
11      0.864
3287    0.864
3917    0.864
3929    0.864
3926    0.864
1955    0.864
1967    0.864
1973    0.864
3938    0.864
3329    0.864
3830    0.864
3827    0.864
3848    0.864
3872    0.864
3245    0.864
683     0.864
677     0.864
689     0.864
4097    0.864
3854    0.864
749     0.864
101     0.864
3311    0.864
3317    0.864
3290    0.864
3200    0.864
38      0.865
35      0.865
32      0.865
71      0.865
65      0.865
3869    0.865
3812    0.865
3815    0.865
3821    0.865
3818    0.865
3833    0.865
3824    0.865
3845    0.865
3878    0.865
3881    0.865
3866    0.865
2561    0.865
2558    0.865
2555    0.865
2582    0.865
2564    0.865
2567    0.865
2570    0.865
2573    0.865
2594    0.865
2615    0.865
2612    0.865
2552    0.865
1412    0.865
400     0.865
728     0.865
3941    0.865
2711    0.865
3698    0.865
1340    0.865
713     0.865
2075    0.865
1316    0.865
1304    0.865
1301    0.865
704     0.865
231     0.865
698     0.865
2843    0.865
2039    0.865
239     0.865
1331    0.865
1346    0.865
2603    0.865
2597    0.865
2624    0.865
2621    0.865
722     0.865
797     0.865
2663    0.865
2657    0.865
3965    0.865
2609    0.865
2090    0.865
782     0.865
1298    0.865
1295    0.865
1292    0.865
821     0.865
1931    0.865
1928    0.865
1925    0.865
665     0.865
3191    0.865
3188    0.865
3185    0.865
3182    0.865
3206    0.865
1964    0.865
161     0.865
1952    0.865
674     0.865
3314    0.865
92      0.865
680     0.865
1937    0.865
1943    0.865
1934    0.865
1982    0.865
137     0.865
662     0.865
1949    0.865
3230    0.865
74      0.865
3194    0.865
3296    0.865
3212    0.865
5       0.865
41      0.865
44      0.865
47      0.865
671     0.865
668     0.865
1922    0.865
1916    0.865
1946    0.865
1988    0.866
1163    0.866
3167    0.866
3581    0.866
3884    0.866
180     0.866
602     0.866
528     0.866
2423    0.866
2231    0.866
2432    0.866
761     0.867
969     0.867
2078    0.867
2852    0.867
2072    0.867
1025    0.867
1430    0.867
371     0.867
386     0.867
3773    0.867
425     0.867
3971    0.867
18      0.867
779     0.867
1595    0.867
2705    0.867
3338    0.867
830     0.867
218     0.867
623     0.867
610     0.867
3065    0.867
1160    0.867
1880    0.867
4016    0.868
4100    0.868
2846    0.868
3695    0.868
2126    0.868
2234    0.868
2720    0.868
208     0.868
3179    0.868
3341    0.868
608     0.868
186     0.868
3050    0.868
158     0.868
1052    0.868
1805    0.868
3353    0.868
615     0.868
3158    0.869
152     0.869
605     0.869
971     0.869
3224    0.869
3209    0.869
404     0.869
2579    0.869
2576    0.869
1487    0.869
3242    0.869
1355    0.869
531     0.869
2606    0.869
554     0.869
10      0.869
695     0.869
89      0.869
686     0.869
318     0.869
2678    0.869
2864    0.869
1283    0.869
2693    0.869
1601    0.869
1688    0.870
229     0.870
3860    0.870
2060    0.870
4106    0.870
287     0.870
2585    0.871
8       0.871
1442    0.871
3923    0.871
2861    0.871
2057    0.871
232     0.871
3293    0.871
2849    0.871
3863    0.871
2111    0.871
4121    0.871
624     0.871
4325    0.871
1991    0.871
2336    0.872
221     0.872
4307    0.872
800     0.872
3842    0.872
747     0.872
416     0.872
435     0.872
4124    0.872
626     0.872
4109    0.872
4328    0.872
627     0.872
3068    0.872
3323    0.872
1235    0.872
3332    0.872
641     0.873
2033    0.873
575     0.873
593     0.873
1352    0.873
2510    0.873
441     0.873
330     0.873
1397    0.873
1349    0.873
2750    0.873
2726    0.873
744     0.873
863     0.873
3482    0.873
2840    0.873
3299    0.873
2210    0.874
2291    0.874
3809    0.874
2213    0.874
2417    0.874
315     0.874
1706    0.874
806     0.874
1049    0.874
222     0.874
833     0.874
3905    0.874
1691    0.874
621     0.874
1598    0.874
4400    0.874
3491    0.874
106     0.874
2318    0.875
234     0.875
1280    0.875
212     0.875
144     0.875
572     0.875
1463    0.875
2123    0.875
1061    0.875
998     0.875
1031    0.875
132     0.875
114     0.875
3053    0.875
397     0.875
2309    0.875
2219    0.875
2534    0.875
2444    0.875
1592    0.876
590     0.876
3677    0.876
390     0.876
4226    0.876
611     0.876
625     0.876
1787    0.876
3770    0.876
334     0.876
124     0.876
205     0.876
3536    0.876
607     0.876
3488    0.876
1184    0.876
3389    0.876
3302    0.876
635     0.876
238     0.877
4331    0.877
4310    0.877
202     0.877
2282    0.877
753     0.877
317     0.877
1811    0.877
599     0.877
2759    0.877
1586    0.877
3950    0.877
2096    0.877
4223    0.877
515     0.877
617     0.877
653     0.877
951     0.877
4397    0.878
854     0.878
160     0.878
215     0.878
3485    0.878
347     0.878
2690    0.878
403     0.878
442     0.878
2429    0.878
534     0.878
1796    0.878
14      0.878
4019    0.878
207     0.878
1484    0.878
398     0.878
576     0.879
401     0.879
299     0.879
2339    0.879
24      0.879
157     0.879
183     0.879
190     0.879
3254    0.879
189     0.879
169     0.879
3368    0.879
3176    0.879
2117    0.879
4103    0.879
613     0.879
1577    0.879
560     0.879
372     0.879
104     0.879
56      0.879
142     0.879
2876    0.879
2744    0.880
3059    0.880
2264    0.880
308     0.880
3755    0.880
594     0.880
22      0.880
1667    0.880
1685    0.880
3914    0.880
544     0.880
574     0.880
2084    0.880
201     0.880
214     0.880
3380    0.880
3566    0.880
236     0.880
4370    0.881
2303    0.881
2426    0.881
592     0.881
579     0.881
408     0.881
405     0.881
368     0.881
424     0.881
353     0.881
385     0.881
1169    0.881
148     0.881
3116    0.881
1168    0.881
1       0.881
3467    0.882
2951    0.882
1046    0.882
177     0.882
154     0.882
181     0.882
187     0.882
4322    0.882
224     0.882
3140    0.882
387     0.882
1679    0.882
573     0.882
577     0.882
1631    0.882
1862    0.882
4391    0.882
4130    0.882
959     0.882
563     0.882
1343    0.882
751     0.882
2918    0.882
3740    0.882
381     0.882
6       0.883
1985    0.883
311     0.883
370     0.883
365     0.883
388     0.883
382     0.883
359     0.883
444     0.883
1589    0.883
1682    0.883
2009    0.883
1073    0.883
1164    0.883
1165    0.883
198     0.883
2921    0.883
225     0.883
3146    0.883
151     0.883
70      0.883
4406    0.883
0       0.883
952     0.884
1802    0.884
361     0.884
3098    0.884
3515    0.884
2924    0.884
2315    0.884
3548    0.884
356     0.884
363     0.884
162     0.884
2909    0.884
2276    0.884
383     0.884
389     0.884
178     0.884
3992    0.884
497     0.884
3362    0.884
195     0.884
1709    0.884
3470    0.884
4112    0.884
1703    0.884
4007    0.884
2741    0.884
369     0.884
3590    0.884
1970    0.884
2522    0.884
1208    0.884
1652    0.884
618     0.885
380     0.885
501     0.885
4196    0.885
4154    0.885
491     0.885
402     0.885
3701    0.885
2495    0.885
1661    0.885
3569    0.885
1155    0.885
423     0.885
418     0.885
561     0.885
4313    0.885
2936    0.885
3557    0.885
2258    0.885
1475    0.885
90      0.885
935     0.885
94      0.885
3728    0.885
619     0.885
163     0.885
3137    0.885
366     0.885
4202    0.885
614     0.885
3596    0.885
763     0.885
2483    0.885
4001    0.885
3524    0.886
1637    0.886
204     0.886
4175    0.886
498     0.886
3365    0.886
2635    0.886
995     0.886
2879    0.886
4319    0.886
1804    0.886
1499    0.886
2498    0.886
375     0.886
433     0.886
426     0.886
213     0.886
3704    0.886
2273    0.886
3074    0.886
756     0.886
2246    0.886
3554    0.886
1808    0.886
377     0.886
949     0.887
2023    0.887
296     0.887
595     0.887
168     0.887
533     0.887
199     0.887
562     0.887
226     0.887
968     0.887
100     0.887
436     0.887
2732    0.887
1493    0.887
448     0.887
3461    0.887
2960    0.887
1658    0.887
3479    0.887
4199    0.887
3551    0.887
2255    0.887
1256    0.887
19      0.887
1159    0.887
1004    0.887
973     0.887
275     0.887
1232    0.887
156     0.887
2930    0.887
1202    0.887
4193    0.887
364     0.887
1790    0.887
644     0.887
1205    0.888
4142    0.888
4145    0.888
848     0.888
4127    0.888
410     0.888
578     0.888
1043    0.888
3383    0.888
192     0.888
589     0.888
384     0.888
596     0.888
2948    0.888
262     0.888
481     0.888
603     0.888
4409    0.888
2435    0.888
1460    0.888
3764    0.888
3       0.888
731     0.888
1976    0.888
945     0.888
358     0.888
954     0.888
1180    0.888
2519    0.888
1365    0.888
1249    0.888
1655    0.888
3907    0.888
1835    0.888
736     0.888
4004    0.889
1958    0.889
1856    0.889
3320    0.889
78      0.889
842     0.889
750     0.889
759     0.889
818     0.889
394     0.889
235     0.889
1325    0.889
420     0.889
1148    0.889
1613    0.889
2108    0.889
379     0.889
1028    0.889
2300    0.889
1865    0.889
637     0.889
719     0.889
1994    0.889
3539    0.889
967     0.889
3251    0.889
304     0.889
3875    0.889
1393    0.889
2882    0.889
4229    0.889
1697    0.890
4178    0.890
4091    0.890
3989    0.890
566     0.890
233     0.890
524     0.890
1156    0.890
1801    0.890
302     0.890
312     0.890
628     0.890
980     0.890
3113    0.890
135     0.890
989     0.890
944     0.890
2321    0.890
300     0.890
857     0.890
538     0.890
2957    0.890
2492    0.890
1253    0.890
1067    0.890
2207    0.890
4163    0.890
3578    0.890
3779    0.890
2735    0.890
4013    0.890
3737    0.890
3913    0.891
584     0.891
503     0.891
4184    0.891
3527    0.891
392     0.891
809     0.891
3377    0.891
1319    0.891
2513    0.891
417     0.891
2486    0.891
290     0.891
3910    0.891
519     0.891
2405    0.891
2891    0.891
2591    0.891
3749    0.891
3839    0.891
3851    0.891
2330    0.891
1817    0.891
1940    0.891
93      0.891
443     0.891
3518    0.891
271     0.891
3119    0.891
2441    0.891
4187    0.891
757     0.891
2870    0.891
1829    0.891
1183    0.891
3599    0.891
3218    0.891
760     0.891
1871    0.891
68      0.892
62      0.892
1841    0.892
1961    0.892
1167    0.892
3998    0.892
3203    0.892
98      0.892
1625    0.892
4298    0.892
2897    0.892
2969    0.892
2312    0.892
716     0.892
1016    0.892
1337    0.892
701     0.892
4151    0.892
588     0.892
378     0.892
598     0.892
3857    0.892
1361    0.892
396     0.892
523     0.892
1064    0.892
4304    0.892
4301    0.892
292     0.892
1211    0.892
754     0.892
518     0.892
734     0.892
95      0.892
4376    0.892
3593    0.892
77      0.892
725     0.892
3215    0.892
2189    0.893
826     0.893
2456    0.893
2249    0.893
3509    0.893
493     0.893
2894    0.893
1196    0.893
1199    0.893
1883    0.893
3271    0.893
2105    0.893
1070    0.893
1676    0.893
1646    0.893
1220    0.893
1058    0.893
2699    0.893
2915    0.893
489     0.893
1868    0.893
97      0.893
2912    0.893
2474    0.893
1472    0.893
640     0.893
1389    0.893
2888    0.893
3128    0.893
1229    0.893
2020    0.893
307     0.893
1241    0.893
96      0.893
1375    0.893
346     0.893
4358    0.893
1889    0.894
4385    0.894
926     0.894
4388    0.894
1847    0.894
1247    0.894
648     0.894
1850    0.894
3572    0.894
3575    0.894
1223    0.894
2885    0.894
4211    0.894
1190    0.894
1193    0.894
2306    0.894
2501    0.894
2516    0.894
2468    0.894
2222    0.894
2963    0.894
4172    0.894
2927    0.894
2261    0.894
2324    0.894
2471    0.894
174     0.894
3107    0.894
522     0.894
4133    0.894
745     0.894
2756    0.894
1421    0.894
3716    0.894
1022    0.894
3110    0.894
3149    0.894
103     0.894
986     0.894
3530    0.895
4181    0.895
2270    0.895
4280    0.895
159     0.895
3713    0.895
1171    0.895
2900    0.895
3563    0.895
517     0.895
513     0.895
2480    0.895
406     0.895
556     0.895
1079    0.895
1571    0.895
1643    0.895
4367    0.895
4088    0.895
2858    0.895
1481    0.895
1496    0.895
1781    0.895
3086    0.895
228     0.895
612     0.895
136     0.895
3752    0.895
3143    0.895
639     0.895
3233    0.895
1886    0.895
932     0.895
4382    0.895
1001    0.896
3104    0.896
3767    0.896
1037    0.896
571     0.896
175     0.896
601     0.896
3542    0.896
4205    0.896
4208    0.896
3452    0.896
3626    0.896
273     0.896
4070    0.896
570     0.896
3077    0.896
1700    0.896
4148    0.896
4139    0.896
4169    0.896
1634    0.896
2165    0.896
3500    0.896
3506    0.896
555     0.896
3458    0.896
4346    0.896
3134    0.896
606     0.896
314     0.896
851     0.896
2465    0.897
2240    0.897
3473    0.897
516     0.897
4343    0.897
506     0.897
293     0.897
3446    0.897
399     0.897
281     0.897
4283    0.897
439     0.897
494     0.897
853     0.897
2942    0.897
1478    0.897
1162    0.897
2873    0.897
509     0.897
2411    0.897
470     0.897
1538    0.897
1258    0.897
3277    0.897
4274    0.897
297     0.897
2017    0.897
1019    0.897
2008    0.897
1760    0.897
1784    0.897
3083    0.897
583     0.897
3440    0.897
1694    0.897
1062    0.897
1742    0.897
4373    0.897
629     0.897
631     0.897
350     0.897
3722    0.897
1844    0.898
655     0.898
3221    0.898
1766    0.898
3038    0.898
245     0.898
242     0.898
3197    0.898
3725    0.898
3707    0.898
2644    0.898
309     0.898
355     0.898
362     0.898
3371    0.898
295     0.898
2738    0.898
580     0.898
569     0.898
413     0.898
464     0.898
467     0.898
458     0.898
461     0.898
257     0.898
2237    0.898
455     0.898
2447    0.898
1490    0.898
1526    0.898
2453    0.898
869     0.898
512     0.898
4079    0.898
452     0.898
266     0.898
269     0.898
82      0.898
75      0.898
351     0.898
153     0.898
3734    0.898
373     0.898
476     0.898
1214    0.898
486     0.898
2294    0.898
3533    0.898
479     0.898
482     0.898
485     0.898
248     0.898
1547    0.898
473     0.898
2834    0.898
272     0.898
860     0.898
254     0.898
251     0.898
1628    0.898
2954    0.898
278     0.898
946     0.899
1670    0.899
2903    0.899
1226    0.899
3125    0.899

In [32]:
temp['accuracy'].sort_values()

2021    0.558
947     0.587
112     0.612
116     0.635
203     0.643
527     0.643
600     0.646
970     0.650
550     0.654
553     0.659
449     0.660
411     0.679
329     0.682
316     0.683
1163    0.688
2642    0.691
1157    0.695
117     0.695
602     0.698
3893    0.703
337     0.705
530     0.705
4217    0.706
1268    0.706
3263    0.709
3692    0.713
125     0.713
219     0.715
127     0.720
115     0.722
130     0.722
440     0.722
211     0.722
526     0.723
126     0.727
647     0.727
972     0.727
2099    0.729
752     0.733
3911    0.737
2645    0.738
318     0.738
1283    0.739
3173    0.739
2       0.739
333     0.740
1381    0.741
1583    0.741
4019    0.742
108     0.744
421     0.744
3587    0.746
2327    0.746
308     0.746
1787    0.746
121     0.747
3068    0.747
2336    0.747
4118    0.748
1055    0.749
17      0.749
3353    0.750
1365    0.750
1280    0.750
340     0.750
1460    0.750
659     0.750
532     0.750
434     0.751
200     0.751
123     0.751
1790    0.751
2507    0.752
1265    0.752
2639    0.752
16      0.753
432     0.753
2087    0.754
966     0.754
431     0.754
4007    0.755
1575    0.755
208     0.755
435     0.755
422     0.755
202     0.755
328     0.756
134     0.756
549     0.756
230     0.757
287     0.757
222     0.757
545     0.757
1286    0.757
343     0.757
4226    0.758
539     0.758
390     0.758
110     0.758
15      0.758
239     0.758
2291    0.759
3383    0.759
3071    0.759
118     0.759
122     0.759
4100    0.760
4       0.760
237     0.761
741     0.761
129     0.761
414     0.762
763     0.763
2726    0.763
90      0.763
3680    0.764
3578    0.766
133     0.766
168     0.766
1589    0.766
27      0.767
4334    0.767
2333    0.768
331     0.768
1898    0.768
3794    0.768
1262    0.769
515     0.769
848     0.769
833     0.769
641     0.769
113     0.769
2069    0.769
3569    0.769
374     0.769
19      0.769
3389    0.769
4403    0.769
854     0.769
236     0.769
3539    0.769
935     0.769
3152    0.769
1376    0.769
2681    0.769
538     0.769
56      0.769
1691    0.769
533     0.769
1688    0.769
491     0.769
373     0.769
167     0.769
2690    0.769
176     0.769
632     0.769
540     0.769
3140    0.769
194     0.769
543     0.769
1169    0.769
209     0.769
207     0.769
2633    0.769
1439    0.769
1436    0.769
1394    0.769
262     0.769
1586    0.769
1409    0.769
1183    0.770
785     0.770
1466    0.770
1676    0.770
3980    0.770
4307    0.770
354     0.770
29      0.770
965     0.770
413     0.770
149     0.770
410     0.770
3788    0.770
1655    0.770
743     0.770
159     0.770
352     0.770
958     0.771
26      0.771
1910    0.771
1061    0.771
1031    0.771
758     0.771
4115    0.773
4109    0.773
2102    0.773
4004    0.773
25      0.773
2741    0.773
234     0.773
3797    0.773
2675    0.774
537     0.774
193     0.774
547     0.774
216     0.774
220     0.774
866     0.774
428     0.774
2018    0.774
529     0.774
3890    0.775
2840    0.775
336     0.775
739     0.775
7       0.775
3155    0.776
587     0.776
4304    0.776
317     0.776
131     0.776
1913    0.776
3884    0.776
656     0.776
218     0.776
3701    0.776
481     0.776
2549    0.776
3158    0.777
1580    0.777
1487    0.777
23      0.777
2000    0.777
2009    0.778
4193    0.778
1484    0.778
1904    0.778
1277    0.778
969     0.779
1166    0.779
620     0.780
3785    0.780
1499    0.780
326     0.780
552     0.780
548     0.780
2750    0.780
223     0.781
3905    0.781
956     0.781
12      0.781
4370    0.781
1168    0.782
132     0.782
4106    0.782
2630    0.783
3146    0.783
755     0.783
330     0.783
1805    0.783
338     0.783
1804    0.783
959     0.783
2654    0.783
954     0.783
2441    0.783
3371    0.784
107     0.784
3995    0.784
28      0.784
232     0.784
4406    0.784
1577    0.785
2435    0.785
332     0.785
4388    0.785
1796    0.785
2438    0.785
3965    0.786
995     0.786
1991    0.786
1694    0.786
759     0.786
1177    0.786
2948    0.786
951     0.787
638     0.787
818     0.787
1856    0.787
535     0.787
427     0.787
2219    0.787
1463    0.787
591     0.787
3       0.788
1841    0.788
3800    0.788
205     0.788
2330    0.788
1370    0.788
2543    0.788
426     0.788
3164    0.788
3170    0.788
320     0.788
2270    0.788
3110    0.788
2315    0.788
1052    0.788
2684    0.788
839     0.788
2885    0.788
24      0.789
321     0.789
3098    0.789
2309    0.789
2756    0.789
1202    0.789
4154    0.789
1063    0.789
4121    0.789
2417    0.789
3749    0.789
541     0.789
437     0.789
3782    0.789
3251    0.789
2519    0.789
3683    0.789
1016    0.789
189     0.789
1802    0.789
10      0.789
3515    0.789
3143    0.790
446     0.790
2042    0.790
1631    0.790
3359    0.790
1808    0.790
3467    0.790
238     0.791
3056    0.791
3053    0.791
2729    0.791
3278    0.791
3488    0.791
1388    0.791
1165    0.792
761     0.792
327     0.792
648     0.792
3302    0.792
635     0.792
1028    0.792
2918    0.792
1604    0.792
347     0.792
1271    0.792
2546    0.793
169     0.793
2225    0.793
3560    0.793
3896    0.794
3052    0.794
2318    0.794
1367    0.794
1814    0.795
2117    0.795
3284    0.795
275     0.795
4223    0.795
745     0.795
4328    0.795
4067    0.795
742     0.795
1781    0.795
3563    0.795
2861    0.795
2717    0.795
3374    0.795
1034    0.796
2843    0.796
4160    0.796
2510    0.796
210     0.796
3260    0.796
613     0.796
1547    0.796
425     0.796
1178    0.796
2870    0.796
3305    0.796
162     0.796
1062    0.796
164     0.796
607     0.796
3887    0.796
803     0.796
1208    0.796
2282    0.796
3971    0.796
369     0.796
371     0.796
575     0.796
1907    0.796
830     0.796
3365    0.796
1077    0.796
1430    0.796
2072    0.796
2048    0.796
2705    0.796
3524    0.796
86      0.796
1       0.796
1889    0.796
3308    0.796
2852    0.796
3326    0.796
2483    0.796
2894    0.796
3542    0.796
3806    0.796
1424    0.796
590     0.796
2264    0.796
2078    0.797
779     0.797
372     0.797
572     0.797
4001    0.797
2753    0.797
344     0.797
325     0.797
594     0.797
3116    0.797
579     0.797
3989    0.797
3908    0.797
3581    0.797
3500    0.797
2735    0.797
644     0.797
2879    0.797
2060    0.797
1050    0.797
2855    0.797
746     0.797
2084    0.797
407     0.797
1598    0.797
106     0.798
109     0.798
1025    0.798
128     0.798
196     0.798
1576    0.798
3728    0.798
20      0.798
863     0.798
4364    0.798
621     0.798
3677    0.798
4124    0.798
3740    0.798
945     0.798
1883    0.798
1901    0.798
1682    0.798
1415    0.799
812     0.799
2528    0.799
393     0.799
1199    0.799
1216    0.799
2420    0.799
625     0.799
4325    0.799
2111    0.799
3737    0.799
3446    0.799
3491    0.799
2216    0.800
322     0.800
1238    0.800
415     0.800
4190    0.801
3386    0.801
517     0.801
1076    0.801
1173    0.801
1172    0.801
1167    0.801
1156    0.801
2525    0.801
3172    0.801
2288    0.801
1289    0.801
604     0.801
1706    0.801
542     0.802
2429    0.802
1036    0.802
4211    0.802
806     0.802
3719    0.802
1021    0.802
953     0.802
1811    0.802
554     0.802
2632    0.802
3983    0.803
2846    0.803
1703    0.803
1709    0.803
341     0.803
418     0.803
1053    0.803
1862    0.803
4333    0.803
3497    0.803
366     0.804
2213    0.804
215     0.804
408     0.804
441     0.804
4394    0.804
160     0.804
1649    0.804
592     0.804
3281    0.804
2837    0.804
4117    0.804
1048    0.804
2017    0.804
4316    0.804
1170    0.805
551     0.805
808     0.805
2297    0.805
845     0.805
3992    0.805
3065    0.805
2957    0.805
1685    0.805
190     0.805
1592    0.805
4016    0.805
335     0.805
2126    0.805
3269    0.805
4175    0.805
525     0.805
3484    0.805
3479    0.805
2720    0.805
4367    0.805
650     0.805
536     0.805
974     0.805
2699    0.806
1070    0.806
753     0.806
893     0.806
1880    0.806
3362    0.806
737     0.806
154     0.806
3527    0.806
1075    0.806
853     0.806
3901    0.806
574     0.806
361     0.806
1179    0.806
1174    0.806
1369    0.807
616     0.807
1634    0.807
3697    0.807
3770    0.807
628     0.807
399     0.807
3101    0.807
1258    0.807
2936    0.807
955     0.807
3377    0.807
2489    0.807
2465    0.807
1250    0.807
2012    0.807
114     0.807
2714    0.807
4409    0.807
3485    0.807
760     0.807
598     0.807
1366    0.807
588     0.807
383     0.808
401     0.808
561     0.808
1180    0.808
420     0.808
4289    0.808
519     0.808
405     0.808
402     0.808
949     0.808
528     0.808
2888    0.808
4136    0.808
4142    0.808
2075    0.808
185     0.808
181     0.808
3290    0.808
740     0.808
195     0.808
2749    0.808
3755    0.808
3257    0.808
3796    0.808
608     0.808
2234    0.808
3902    0.808
3917    0.808
3920    0.808
1444    0.808
1385    0.808
800     0.808
584     0.808
363     0.808
1372    0.808
950     0.808
962     0.808
3332    0.808
3347    0.808
4391    0.808
2627    0.808
14      0.808
4400    0.809
683     0.809
2648    0.809
1994    0.809
1973    0.809
2006    0.809
93      0.809
3482    0.809
3551    0.809
1817    0.809
3536    0.809
3554    0.809
101     0.809
2024    0.809
3344    0.809
95      0.809
2051    0.809
153     0.809
151     0.809
2023    0.809
140     0.809
2015    0.809
135     0.809
157     0.809
3335    0.809
2045    0.809
1700    0.809
2030    0.809
1679    0.809
2081    0.809
2723    0.809
3317    0.809
299     0.809
212     0.809
235     0.809
227     0.809
3698    0.809
180     0.809
179     0.809
178     0.809
191     0.809
3707    0.809
1646    0.809
197     0.809
3764    0.809
3287    0.809
221     0.809
214     0.809
1451    0.809
1418    0.809
3926    0.809
1526    0.809
3791    0.809
224     0.809
3272    0.809
1379    0.809
1384    0.809
3161    0.809
1403    0.809
1393    0.809
3944    0.809
744     0.809
295     0.809
296     0.809
2960    0.809
1181    0.809
417     0.809
416     0.809
611     0.809
788     0.809
368     0.809
2303    0.809
395     0.809
311     0.809
307     0.809
3950    0.809
1343    0.809
1352    0.809
1358    0.809
1355    0.809
3089    0.809
2744    0.809
623     0.809
323     0.809
3968    0.809
3977    0.809
1313    0.809
3137    0.809
1307    0.809
339     0.809
2600    0.809
375     0.809
764     0.809
353     0.809
358     0.809
365     0.809
1073    0.809
1175    0.809
4079    0.809
397     0.809
386     0.809
389     0.809
1211    0.809
1190    0.809
400     0.809
382     0.809
524     0.809
518     0.809
2702    0.809
4199    0.809
4313    0.809
544     0.809
2876    0.809
501     0.809
1022    0.809
513     0.809
998     0.809
4172    0.809
2927    0.809
2864    0.809
1019    0.809
2921    0.809
483     0.809
583     0.809
589     0.809
597     0.809
2915    0.809
1043    0.809
2669    0.809
2666    0.809
570     0.809
836     0.809
2537    0.809
534     0.809
516     0.809
971     0.809
563     0.809
2498    0.809
932     0.809
944     0.809
573     0.809
577     0.809
1196    0.810
791     0.810
3548    0.810
2003    0.810
2002    0.810
186     0.810
1601    0.810
3518    0.810
356     0.810
3092    0.810
324     0.810
1337    0.810
1373    0.810
626     0.810
342     0.810
3176    0.810
1433    0.810
2228    0.810
1058    0.810
2426    0.810
2444    0.810
447     0.810
824     0.810
497     0.810
0       0.811
864     0.811
756     0.811
4013    0.811
3688    0.811
359     0.811
384     0.811
1249    0.811
206     0.811
1472    0.811
2477    0.811
2969    0.811
2516    0.811
319     0.811
3350    0.811
412     0.811
3575    0.811
18      0.811
2273    0.811
229     0.811
105     0.811
4358    0.811
1454    0.811
3704    0.811
3050    0.812
1697    0.812
1868    0.812
776     0.812
424     0.812
1766    0.812
1223    0.812
2255    0.812
2900    0.812
655     0.812
3682    0.812
1445    0.812
4373    0.812
3545    0.812
3716    0.812
1667    0.812
2008    0.812
1229    0.812
2651    0.812
1571    0.812
3962    0.812
1595    0.813
1496    0.813
144     0.813
938     0.813
2501    0.813
615     0.813
377     0.813
1892    0.813
3956    0.813
3470    0.813
3476    0.813
2672    0.813
1613    0.813
3743    0.813
111     0.813
2849    0.813
627     0.813
388     0.813
1247    0.813
119     0.813
4151    0.813
183     0.813
1997    0.813
829     0.813
4310    0.813
170     0.813
21      0.813
3935    0.813
3899    0.814
3773    0.814
493     0.814
4397    0.814
2014    0.814
4319    0.814
750     0.814
1874    0.814
1234    0.814
560     0.814
177     0.814
2480    0.814
1652    0.814
3803    0.814
619     0.814
957     0.814
983     0.814
3107    0.814
1871    0.814
380     0.814
2258    0.814
2261    0.814
498     0.815
3914    0.815
3842    0.815
1389    0.815
4196    0.815
304     0.815
1383    0.815
3271    0.815
1259    0.815
1622    0.815
6       0.815
2822    0.815
1322    0.815
2696    0.815
2267    0.815
923     0.815
1182    0.815
3380    0.815
2432    0.815
747     0.815
967     0.815
1670    0.815
578     0.815
2759    0.815
1072    0.815
1046    0.815
624     0.815
546     0.816
3475    0.816
2120    0.816
1581    0.816
184     0.816
385     0.816
1205    0.816
531     0.816
815     0.816
1789    0.816
120     0.816
810     0.816
1390    0.816
1145    0.816
2020    0.816
2423    0.816
3892    0.816
994     0.816
3494    0.816
4321    0.816
4133    0.816
4157    0.816
1794    0.816
3283    0.816
148     0.816
142     0.816
4082    0.816
2246    0.816
2016    0.816
1368    0.817
89      0.817
3338    0.817
430     0.817
1895    0.817
4205    0.817
754     0.817
2828    0.817
1235    0.817
213     0.817
990     0.817
225     0.817
838     0.817
1999    0.817
2231    0.817
2005    0.817
3275    0.817
2951    0.817
3455    0.817
2279    0.817
1024    0.817
1391    0.817
1078    0.817
1382    0.817
1248    0.818
156     0.818
442     0.818
822     0.818
3266    0.818
4214    0.818
174     0.818
403     0.818
404     0.818
2653    0.818
1252    0.818
3256    0.818
2123    0.818
1232    0.818
1596    0.818
3907    0.818
188     0.818
634     0.818
751     0.818
1806    0.818
1448    0.818
2206    0.818
2641    0.818
1799    0.818
3461    0.818
1619    0.819
852     0.819
3379    0.819
2813    0.819
4130    0.819
3953    0.819
3904    0.819
1255    0.819
1877    0.819
946     0.819
1594    0.819
3062    0.819
2027    0.819
3596    0.819
4262    0.819
562     0.819
2860    0.819
364     0.819
146     0.819
231     0.819
1919    0.819
3416    0.819
3134    0.819
840     0.819
1164    0.819
727     0.819
187     0.819
973     0.819
1535    0.819
606     0.819
1184    0.820
423     0.820
3584    0.820
2708    0.820
70      0.820
639     0.820
1800    0.820
2339    0.820
429     0.820
4343    0.820
1597    0.820
1253    0.820
631     0.820
104     0.820
1812    0.820
2825    0.820
152     0.820
175     0.820
3061    0.820
2207    0.820
1045    0.821
1027    0.821
2419    0.821
1886    0.821
3487    0.821
2687    0.821
378     0.821
3932    0.821
595     0.821
302     0.821
2531    0.821
2054    0.821
2462    0.821
1371    0.821
1671    0.821
3913    0.821
3986    0.821
605     0.821
789     0.821
4000    0.821
1801    0.821
576     0.821
2456    0.822
749     0.822
1237    0.822
1603    0.822
2224    0.822
3998    0.822
1282    0.822
1690    0.822
3046    0.822
182     0.822
2638    0.822
2636    0.822
1193    0.822
748     0.822
198     0.822
3599    0.822
443     0.822
3280    0.822
861     0.823
1565    0.823
3751    0.823
3566    0.823
926     0.823
2660    0.823
1475    0.823
201     0.823
948     0.823
3073    0.823
1903    0.823
968     0.823
3049    0.823
1658    0.823
1792    0.823
1829    0.823
2939    0.823
1462    0.823
2920    0.823
2071    0.823
1241    0.823
3274    0.823
3119    0.823
2647    0.823
2732    0.823
2839    0.823
486     0.823
1064    0.823
1481    0.824
1133    0.824
980     0.824
2198    0.824
3329    0.824
4145    0.824
3590    0.824
3644    0.824
4103    0.824
1162    0.824
823     0.824
523     0.824
3776    0.824
228     0.824
580     0.824
4114    0.824
603     0.824
3481    0.824
309     0.824
233     0.824
1803    0.824
394     0.824
2300    0.824
1220    0.824
392     0.824
3059    0.824
448     0.824
3355    0.824
334     0.824
1387    0.824
3722    0.824
2747    0.824
860     0.824
3641    0.824
158     0.824
355     0.824
290     0.824
1049    0.824
4331    0.824
489     0.824
94      0.824
859     0.824
1044    0.824
2513    0.825
2533    0.825
3067    0.825
3178    0.825
1127    0.825
3694    0.825
1257    0.825
2204    0.825
4229    0.825
849     0.825
315     0.825
1158    0.825
782     0.825
2930    0.825
4091    0.825
2210    0.825
2858    0.825
637     0.825
1204    0.825
2312    0.825
4187    0.825
1702    0.825
2415    0.825
4312    0.825
3268    0.825
4163    0.825
4330    0.825
264     0.826
265     0.826
952     0.826
261     0.826
1228    0.826
4385    0.826
436     0.826
3029    0.826
4096    0.826
2405    0.826
141     0.826
504     0.826
2195    0.826
1897    0.826
1378    0.826
2963    0.826
3679    0.826
2240    0.826
3316    0.826
163     0.826
370     0.826
617     0.826
1493    0.826
1375    0.826
147     0.826
444     0.826
2416    0.826
599     0.826
963     0.826
2183    0.826
55      0.826
391     0.826
3254    0.826
4225    0.826
3248    0.826
2053    0.826
3227    0.826
3245    0.826
4010    0.826
827     0.826
1251    0.826
1574    0.826
2276    0.826
300     0.826
1041    0.826
4376    0.826
1988    0.826
3443    0.826
3262    0.826
3872    0.826
75      0.826
192     0.826
379     0.826
1226    0.826
618     0.826
2422    0.826
1349    0.826
1650    0.827
796     0.827
757     0.827
3685    0.827
3149    0.827
2425    0.827
2033    0.827
2162    0.827
2321    0.827
784     0.827
409     0.827
3490    0.827
3323    0.827
1397    0.827
985     0.827
3166    0.827
4361    0.827
2233    0.827
850     0.827
719     0.827
989     0.827
3167    0.827
3299    0.827
1066    0.827
3533    0.827
868     0.827
3083    0.828
3809    0.828
2129    0.828
3356    0.828
1876    0.828
565     0.828
555     0.828
4382    0.828
646     0.828
1976    0.828
2503    0.828
2873    0.828
2692    0.828
3473    0.828
2663    0.828
826     0.828
362     0.828
350     0.828
346     0.828
345     0.828
3128    0.828
3125    0.828
2090    0.828
3320    0.828
360     0.828
773     0.828
4181    0.828
2882    0.828
2486    0.828
1643    0.828
3752    0.828
3746    0.828
792     0.828
2294    0.828
2066    0.828
3964    0.828
2285    0.828
351     0.828
3686    0.828
2924    0.828
1844    0.828
199     0.828
1637    0.828
1001    0.828
3521    0.828
805     0.828
3910    0.828
1004    0.828
4184    0.828
3074    0.828
3293    0.828
3064    0.828
2036    0.828
2222    0.828
593     0.828
585     0.828
3530    0.828
3557    0.828
3941    0.828
3938    0.828
97      0.828
171     0.828
166     0.828
2644    0.828
3314    0.828
612     0.828
2725    0.828
3296    0.828
601     0.828
419     0.828
1160    0.828
137     0.828
136     0.828
145     0.828
438     0.828
124     0.828
1406    0.828
11      0.828
581     0.828
568     0.828
674     0.829
57      0.829
1922    0.829
3419    0.829
1946    0.829
1949    0.829
1952    0.829
2573    0.829
571     0.829
226     0.829
1607    0.829
58      0.829
59      0.829
60      0.829
2570    0.829
3452    0.829
2678    0.829
1937    0.829
1943    0.829
5       0.829
8       0.829
47      0.829
48      0.829
1961    0.829
32      0.829
35      0.829
3440    0.829
1931    0.829
665     0.829
1788    0.829
139     0.829
1784    0.829
3959    0.829
3961    0.829
1412    0.829
2996    0.829
4070    0.829
1148    0.829
143     0.829
150     0.829
1742    0.829
1159    0.829
2990    0.829
2993    0.829
698     0.829
701     0.829
704     0.829
1751    0.829
662     0.829
469     0.829
3700    0.829
1661    0.829
172     0.829
173     0.829
3923    0.829
2450    0.829
4139    0.829
4148    0.829
4127    0.829
2408    0.829
1832    0.829
2912    0.829
470     0.829
2621    0.829
1400    0.829
2603    0.829
2609    0.829
2612    0.829

In [14]:
dt.classes_

array([0, 1])

In [15]:
dt.max_features_

6

In [16]:
dt.n_classes_

np.int64(2)

In [17]:
dt.n_features_in_

13

In [18]:
dt.feature_importances_

array([0.        , 0.03495541, 0.21965201, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07569266, 0.        , 0.66969992])

In [24]:
dt.n_outputs_

1

In [27]:
dt.tree_

## Grid Search CV

In [7]:
# param_grid = {
#     'splitter': ['best', 'random'],
#     'criterion': ['gini', 'entropy', 'log_loss'],
#     'max_features': ['sqrt', 'log2', None, 0.5,0.8],
#     'max_depth': [3, 5, 7, 10,12, None],
#     'ccp_alpha': [0.0, 0.001, 0.01],
#     'min_samples_leaf': [1, 2, 5],
#     'min_samples_split': [2, 5, 10]
# }

# scoring = {
#     'acc': 'accuracy',
#     'prec': 'precision',
#     'rec': 'recall',
#     'f1': 'f1',
#     'auc': 'roc_auc'
# }

# grid = GridSearchCV(
#     DecisionTreeClassifier(),
#     param_grid,
#     cv = 5,
#     n_jobs=-1,
#     scoring=scoring,
#     refit = False
    
# )
# grid.fit(x_train,y_train)
# new_df = pd.DataFrame(grid.cv_results_)

## Randomized Search CV

In [10]:
param_distributions = {
    'splitter': ['best', 'random'],
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_features': ['sqrt', 'log2', None, 0.5,0.8],
    'max_depth': [3, 5, 7, 10,12, None],
    'ccp_alpha': [0.0, 0.001, 0.01],
    'min_samples_leaf': [1, 2, 5],
    'min_samples_split': [2, 5, 10]
}

scoring = {
    'acc': 'accuracy',
    'prec': 'precision',
    'rec': 'recall',
    'f1': 'f1',
    'auc': 'roc_auc'
}

random_grid = RandomizedSearchCV(
    DecisionTreeClassifier(),
    param_distributions,
    n_jobs=-1,
    scoring=scoring,
    refit=False,
    cv = 5
)

random_grid.fit(x_train,y_train)
temp_df = pd.DataFrame(random_grid.cv_results_)

In [11]:
temp_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_splitter,param_min_samples_split,param_min_samples_leaf,param_max_features,param_max_depth,param_criterion,param_ccp_alpha,params,split0_test_acc,split1_test_acc,split2_test_acc,split3_test_acc,split4_test_acc,mean_test_acc,std_test_acc,rank_test_acc,split0_test_prec,split1_test_prec,split2_test_prec,split3_test_prec,split4_test_prec,mean_test_prec,std_test_prec,rank_test_prec,split0_test_rec,split1_test_rec,split2_test_rec,split3_test_rec,split4_test_rec,mean_test_rec,std_test_rec,rank_test_rec,split0_test_f1,split1_test_f1,split2_test_f1,split3_test_f1,split4_test_f1,mean_test_f1,std_test_f1,rank_test_f1,split0_test_auc,split1_test_auc,split2_test_auc,split3_test_auc,split4_test_auc,mean_test_auc,std_test_auc,rank_test_auc
0,1.016072,0.144186,0.366807,0.015335,best,5,5,sqrt,3,log_loss,0.000,"{'splitter': 'best', 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'max_depth': 3, 'criterion': 'log_loss', 'ccp_alpha': 0.0}",0.774002,0.797166,0.778934,0.824898,0.741961,0.783392,0.027339,10,0.765908,0.743346,0.779849,0.801044,0.901371,0.798303,0.054847,10,0.714463,0.836590,0.706550,0.811007,0.476844,0.709091,0.126978,10,0.739291,0.787216,0.741392,0.805995,0.623725,0.739524,0.063413,10,0.851863,0.854785,0.837355,0.885994,0.800664,0.846132,0.027717,10
1,3.115783,0.044410,0.593250,0.019108,random,10,5,0.5,None,log_loss,0.000,"{'splitter': 'random', 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 0.5, 'max_depth': None, 'criterion': 'log_loss', 'ccp_alpha': 0.0}",0.872971,0.873061,0.873741,0.874399,0.871757,0.873186,0.000881,1,0.874021,0.871013,0.871274,0.869119,0.867886,0.870662,0.002091,1,0.837475,0.841596,0.843037,0.847587,0.842282,0.842395,0.003232,1,0.855358,0.856052,0.856923,0.858218,0.854892,0.856288,0.001183,1,0.934127,0.932942,0.934766,0.932769,0.932799,0.933480,0.000816,2
2,1.123010,0.050870,0.370272,0.007937,random,2,1,log2,7,gini,0.000,"{'splitter': 'random', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': 7, 'criterion': 'gini', 'ccp_alpha': 0.0}",0.833231,0.844399,0.837528,0.844717,0.843571,0.840689,0.004559,6,0.871709,0.843570,0.839337,0.853689,0.811733,0.844007,0.019620,6,0.736557,0.801729,0.788710,0.788988,0.847869,0.792771,0.035516,6,0.798454,0.822117,0.813236,0.820064,0.829408,0.816656,0.010460,6,0.905208,0.913366,0.898683,0.912541,0.916428,0.909245,0.006439,5
3,1.007275,0.055630,0.377778,0.023254,best,5,1,log2,3,log_loss,0.010,"{'splitter': 'best', 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2', 'max_depth': 3, 'criterion': 'log_loss', 'ccp_alpha': 0.01}",0.815556,0.817392,0.829909,0.804399,0.817721,0.816995,0.008102,8,0.890192,0.786876,0.803425,0.815980,0.807029,0.820701,0.036002,9,0.671588,0.813055,0.821827,0.728063,0.780120,0.762931,0.056278,7,0.765591,0.799751,0.812522,0.769519,0.793347,0.788146,0.017953,8,0.882376,0.869473,0.886476,0.857067,0.873912,0.873861,0.010324,9
4,3.613684,0.029717,0.743321,0.007638,random,5,1,0.5,None,log_loss,0.000,"{'splitter': 'random', 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5, 'max_depth': None, 'criterion': 'log_loss', 'ccp_alpha': 0.0}",0.843118,0.843776,0.841383,0.840964,0.842676,0.842383,0.001056,5,0.850390,0.845958,0.843689,0.844163,0.845485,0.845937,0.002376,4,0.789013,0.796749,0.793311,0.791516,0.794403,0.792998,0.002616,5,0.818553,0.820616,0.817725,0.816992,0.819149,0.818607,0.001243,5,0.876987,0.877727,0.876730,0.875590,0.876575,0.876722,0.000690,8
5,1.318922,0.087773,0.362767,0.019867,random,5,1,None,3,gini,0.001,"{'splitter': 'random', 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None, 'max_depth': 3, 'criterion': 'gini', 'ccp_alpha': 0.001}",0.827483,0.838776,0.830227,0.830397,0.826304,0.830637,0.004363,7,0.809438,0.867618,0.882710,0.882836,0.806888,0.849898,0.034533,3,0.804813,0.755846,0.716687,0.716991,0.805501,0.759968,0.039551,8,0.807119,0.807885,0.791082,0.791317,0.806194,0.800719,0.007792,7,0.888034,0.884938,0.882396,0.884915,0.895765,0.887210,0.004636,6
6,1.526193,0.028947,0.384416,0.011613,random,10,5,log2,10,entropy,0.001,"{'splitter': 'random', 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'log2', 'max_depth': 10, 'criterion': 'entropy', 'ccp_alpha': 0.001}",0.846995,0.850023,0.847279,0.847052,0.846633,0.847596,0.001231,4,0.844116,0.837837,0.826536,0.841791,0.815443,0.833145,0.010716,7,0.808074,0.825341,0.834644,0.811487,0.850549,0.826019,0.015555,4,0.825702,0.831542,0.830570,0.826361,0.832626,0.829360,0.002802,4,0.915437,0.920146,0.907910,0.912989,0.916087,0.914514,0.004025,4
7,1.726102,0.116328,0.342315,0.040222,random,10,5,0.8,5,entropy,0.001,"{'splitter': 'random', 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 0.8, 'max_depth': 5, 'criterion': 'entropy', 'ccp_alpha': 0.001}",0.847098,0.854694,0.858005,0.855782,0.857052,0.854526,0.003880,3,0.858089,0.844521,0.836290,0.828925,0.856312,0.844827,0.011257,5,0.789671,0.828551,0.849736,0.854868,0.818646,0.828294,0.023456,3,0.822459,0.836460,0.842959,0.841697,0.837055,0.836126,0.007287,3,0.921306,0.924263,0.927840,0.923400,0.927600,0.924882,0.002510,3
8,1.375803,0.212878,0.179183,0.044491,best,10,2,sqrt,7,entropy,0.010,"{'splitter': 'best', 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 7, 'criterion': 'entropy', 'ccp_alpha': 0.01}",0.806440,0.819127,0.819467,0.820385,0.800159,0.813116,0.008268,9,0.839807,0.806021,0.831324,0.822662,0.825691,0.825101,0.011183,8,0.702404,0.785828,0.749551,0.764264,0.702791,0.740968,0.033387,9,0.764984,0.795796,0.788323,0.792389,0.759300,0.780158,0.015007,9,0.873075,0.898589,0.879917,0.901686,0.873787,0.885411,0.012297,7
9,3.017952,0.066545,0.117509,0.004884,best,2,2,None,12,log_loss,0.001,"{'splitter': 'best', 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': None, 'max_depth': 12, 'criterion': 'log_loss', 'ccp_alpha': 0.001}",0.866406,0.864161,0.865975,0.864683,0.862528,0.864751,0.001381,2,0.858522,0.857387,0.859498,0.856321,0.858461,0.858038,0.001088,2,0.840660,0.836211,0.838183,0.839068,0.830401,0.836905,0.003555,2,0.849497,0.846667,0.848707,0.847607,0.844198,0.847335,0.001840,2,0.936158,0.936107,0.936980,0.936765,0.935600,0.936322,0.000495,1